**Import Required Libraries**

In [9]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression

**Loading The Dataset**

In [3]:
df = pd.read_csv("/content/employee_salary_prediction_utf8.csv")

**Displaying First 5 Rows of Dataset**

In [4]:
df.head()

   Employee_ID  Age  YearsExperience Department  Salary
0            1   29              9.5      Sales   93382
1            2   37              5.6      Sales   71700
2            3   44             11.0         HR  108807
3            4   38              3.8      Sales   55938
4            5   30              7.6         IT   85156

**Dataset Information**

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Employee_ID      100 non-null    int64
 1   Age              100 non-null    int64
 2   YearsExperience  100 non-null    float64
 3   Department       100 non-null    object
 4   Salary           100 non-null    int64
dtypes: float64(1), int64(3), object(1)
memory usage: 4.0+ KB

**Statistical Summary**

In [6]:
df.describe()

       Employee_ID         Age  YearsExperience         Salary
count   100.000000  100.000000       100.000000     100.000000
mean     50.500000   35.650000         8.529000   89504.840000
std      29.011492    8.398382         3.824913   26792.120221
min       1.000000   21.000000         1.200000   40058.000000
25%      25.750000   28.750000         5.575000   70542.250000
50%      50.500000   35.000000         8.100000   85867.000000
75%      75.250000   42.250000        11.850000  112285.750000
max     100.000000   50.000000        15.000000  137915.000000

**Checking Missing Values**

In [7]:
df.isnull().sum()

Employee_ID        0
Age                0
YearsExperience    0
Department         0
Salary             0
dtype: int64

**Removing Missing Values**

In [31]:
df.dropna(inplace=True)

**Selecting Features For Prediction**

In [39]:
X = df[["Age", "YearsExperience"]]

**Defining Target Variable**

In [32]:
y = df["Salary"]

**Initializing Linear Regression Model**

In [33]:
model = LinearRegression()

**Training the Machine Learning Model**

In [34]:
model.fit(X, y)

LinearRegression()

**Taking User Input**

In [35]:
age = float(input("Enter Your Age: "))
YearsExperience = float(input("Enter Experience in Years (6 months = 0.5): "))

Enter Your Age: 25
Enter Experience in Years (6 months = 0.5): 3

**Predicting Employee Salary**

In [37]:
predicition = model.predict([[age, YearsExperience]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

**Final Output**

In [38]:
print("\nPredicted Salary = ₹", round(predicition[0]))

Predicted Salary = ₹ 50840